apiVersion: v1
kind: Service
metadata:
  name: gemtc
  namespace: addis-poc-devtest
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 3001
  selector:
    app: gemtc
