apiVersion: apps/v1
kind: Deployment
metadata:
  name: patavi-server
  namespace: addis-poc-devtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patavi-server
  template:
    metadata:
      labels:
        app: patavi-server
    spec:
      volumes:
      - name: ssl-certificates
        configMap:
          name: certs
          items:
          - key: crt.pem
            path: crt.pem
          - key: key.pem
            path: key.pem
          - key: ca-crt.pem
            path: ca-crt.pem
      containers:
      - name: patavi-server
        image: addis/patavi-server
        volumeMounts:
        - name: certs
          mountPath: /var/lib/patavi/ssl
        envFrom:
        - configMapRef:
            name: patavi-settings
        env:
        - name: PATAVI_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: PATAVI_DB_PASSWORD
        ports:
        - name: patavi-server
          containerPort: 3000