apiVersion: v1
kind: Service
metadata:
  name: patavi-server
  namespace: addis-poc-devtest
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: patavi-server
