apiVersion: v1
kind: Pod
metadata:
  name: gemtc-db-init
  namespace: addis-poc-devtest
  labels:
    app: gemtc-db-init
spec:
  imagePullSecrets:
  - name: registry-credentials
  initContainers:
  - name: wait-for-db
    image: postgres:10.8
    env:
    - name: PGUSER
      value: postgres
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: POSTGRES_PASSWORD
    command: ['sh', '-c']
    args:
     - until psql -h postgres -c  "select version();"; do echo waiting for postgres; sleep 2; done;
  - name: create-gemtc-user
    image: postgres:10.8
    env:
    - name: PGUSER
      value: postgres
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: POSTGRES_PASSWORD
    - name: GEMTC_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: GEMTC_DB_PASSWORD
    command: ['sh', '-c']
    args:
     - psql -h postgres -c  "CREATE USER gemtc WITH PASSWORD '$(GEMTC_DB_PASSWORD)'" -c  "CREATE database gemtc encoding 'utf-8'"
  restartPolicy: Never
  containers:
  - name: run-liquibase
    image: registry.drugis.org/liquibase-gemtc
    env: 
    - name: LIQUIBASE_URL
      value: 'jdbc:postgresql://postgres:5432/gemtc'
    - name: LIQUIBASE_USERNAME
      value: "gemtc"
    - name: LIQUIBASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: GEMTC_DB_PASSWORD
