apiVersion: v1
kind: Service
metadata:
  name: patavi-server
  namespace: gemtc
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: patavi-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patavi-server
  namespace: gemtc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patavi-server
  template:
    metadata:
      labels:
        app: patavi-server
    spec:
      containers:
      - name: patavi-server
        image: addis/patavi-server
        envFrom:
        - configMapRef:
            name: patavi-settings
        env:
        - name: PATAVI_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: PATAVI_DB_PASSWORD
        ports:
        - name: patavi-server
          containerPort: 3000
